ALTER TABLE Users
ADD UNIQUE (Username);

ALTER TABLE Users
ADD UNIQUE (Email);

ALTER TABLE Loggers
ADD UNIQUE ("Event");

ALTER TABLE Posts
ADD CONSTRAINT User_ID_fk
FOREIGN KEY (User_ID)
REFERENCES Users ("ID");

ALTER TABLE "Comments"
ADD CONSTRAINT Post_ID_fk
FOREIGN KEY (Post_ID)
REFERENCES Posts ("ID");

ALTER TABLE "Comments"
ADD CONSTRAINT User_ID_fk
FOREIGN KEY (User_ID)
REFERENCES Users ("ID");

ALTER TABLE Likes
ADD CONSTRAINT Post_ID_fk
FOREIGN KEY (Post_ID)
REFERENCES Posts ("ID");

ALTER TABLE Likes
ADD CONSTRAINT User_ID_fk
FOREIGN KEY (User_ID)
REFERENCES Users ("ID");