CREATE TABLE Users (
    "ID" UUID PRIMARY KEY DEFAULT
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    "Password" VARCHAR(255) NOT NULL,
    Created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE Posts (
    "ID" UUID PRIMARY KEY DEFAULT,
    User_ID UUID,
    "Content" TEXT NOT NULL,
    Created_at TIMESTAMP DEFAULT NOW(),
	CONSTRAINT User_ID_fk FOREIGN KEY (User_ID) 
		REFERENCES Users ("ID")
);

CREATE TABLE "Comments" (
    "ID" UUID PRIMARY KEY DEFAULT,
    Post_ID UUID,
    User_ID UUID,
    Text TEXT NOT NULL,
    Created_at TIMESTAMP DEFAULT NOW(),
	CONSTRAINT Post_ID_fk FOREIGN KEY (Post_ID)
		REFERENCES Posts ("ID"),
	CONSTRAINT User_ID_fk FOREIGN KEY (User_ID)
		REFERENCES Users ("ID")
);

CREATE TABLE Likes (
    "ID" UUID PRIMARY KEY DEFAULT,
    Post_ID UUID,
    User_ID UUID,
	CONSTRAINT Post_ID_fk FOREIGN KEY (Post_ID) 
		REFERENCES Posts ("ID"),
	CONSTRAINT User_ID_fk FOREIGN KEY (User_ID) 
		REFERENCES Users ("ID")
);

CREATE TABLE Loggers (
	"Event" TEXT UNIQUE
);