package ru.vsu.amm.java;

public enum Fio {
    GARSHIN_MAKSIM_SERGEEVICH,
    GADSHIEV_MAKSIM_DENISOVICH,
    AKSENOV_MAKSIM_ALEKSANDROVICH,
    KIIKO_MAKSIM_VADIMOVICH,
    KANATNIKOV_MAKSIM_ANDREEVICH,
    POZNDIKOV_MAKSIM_MAKSIMOVICH
}
