package ru.vsu.amm.java;

public enum Course {
    MATHEMATICAL_ANALYSIS,
    ALGEBRA,
    COMPUTER_SCIENCE,
    NUMERICAL_METHODS,
    DIFFERENTIAL_EQUATIONS,
    PROBABILITY_THEORY,
    FUNCTIONAL_ANALYSIS
}
